[default.general]
chip = "RP2040"
# RP2040 does not support connect_under_reset
connect_under_reset = false

[default.probe]
protocol = "Swd"
speed = 20000

[default.rtt]
enabled = false
# timeout = 3000

[default.reset]
halt_afterwards = false

[default.gdb]
enabled = true
